// <auto-generated />
namespace AspNetIdentity.WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changedatabaseaddnew2tableclientandrefreshtoken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedatabaseaddnew2tableclientandrefreshtoken));
        
        string IMigrationMetadata.Id
        {
            get { return "201509211427489_change database add new 2 table client and refreshtoken"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
